// <auto-generated />
using System;
using DnDHooksFullStack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DnDHooksFullStack.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DnDHooksFullStack.Models.LevelTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxXP")
                        .HasColumnType("integer");

                    b.Property<int>("MinXP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LevelTracker");
                });

            modelBuilder.Entity("DnDHooksFullStack.Models.SessionTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CombatXP")
                        .HasColumnType("integer");

                    b.Property<int>("ExplorationXP")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SessionDescription")
                        .HasColumnType("text");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SocialInteractionXP")
                        .HasColumnType("integer");

                    b.Property<int>("XPId")
                        .HasColumnType("integer");

                    b.Property<int?>("XPTrackerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("XPTrackerId");

                    b.ToTable("SessionTracker");
                });

            modelBuilder.Entity("DnDHooksFullStack.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DnDHooksFullStack.Models.XPTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("TotalLevel")
                        .HasColumnType("integer");

                    b.Property<int>("TotalXP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("XPTracker");
                });

            modelBuilder.Entity("DnDHooksFullStack.Models.SessionTracker", b =>
                {
                    b.HasOne("DnDHooksFullStack.Models.XPTracker", "XPTracker")
                        .WithMany("Sessions")
                        .HasForeignKey("XPTrackerId");
                });
#pragma warning restore 612, 618
        }
    }
}
